site_name: Ruanyf Weekly
theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/git-alt

  palette:

    # Toggle light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: 浅色模式

    # Toggle dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: 深色模式

  language: zh

  features:
    - navigation.tabs
    - navigation.expand

repo_url: https://github.com/ruanyf/weekly
repo_name: ruanyf/weekly

extra:
  generator: false
  
nav:
  - 首页: index.md
