name: Sync and Deploy MkDocs

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 4 * * 5' # 每周五 UTC 时间凌晨 4 点
  workflow_dispatch:

jobs:
  sync_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/ruanyf/weekly.git
          git fetch upstream

      - name: Merge upstream/master
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories --strategy-option theirs # 在冲突时总是采用上游的修改

      - name: Update README.md to docs/index.md
        run: |
          cp README.md docs/index.md

      - name: Sort and rename files
        run: |
          python sort_and_rename.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material pyyaml

      - name: Check renamed files
        run: ls docs

      - name: Display mkdocs.yml
        run: cat mkdocs.yml

      - name: Build MkDocs
        run: mkdocs build

      - name: Deploy MkDocs to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs gh-deploy --force
